### ISSUE TITLE
Export CSV: empty file created with 0 bytes

### ISSUE THREAD

**Issue by JStratil** [ghalter/VIAN#278] opened 2020-04-15 10:16 UTC
When exporting a CSV from a current project an empty file is created with 0 bytes (path documents/projects/PROJECT_TITLE/)

Used:
VIAN, Version:    0.8.16, on mac OS Mojave.

Are any pre-selections necessary or further selection options needed?

**Comment by ghalter** [comment] 2020-04-15 10:24
Hmm, should not be necessary.
Can you post your .eext file here?

**Comment by JStratil** [comment] 2020-04-15 10:30
I have difficulties posting the file type here. Send you via mail?

**Comment by JStratil** [comment] 2020-04-15 10:30
[Capitalism.eext.zip](https://github.com/ghalter/VIAN/files/4480625/Capitalism.eext.zip)

**Comment by ghalter** [comment] 2020-04-15 10:35
Have you specified the .csv file type at the end, I just realized that the file type is not appended if not given, in [CSVExporter](https://github.com/ghalter/VIAN/blob/d5ae3b3083373c1f66db0875e41fe6fd17e06d61/core/data/exporters.py#L268)

**Comment by JStratil** [comment] 2020-04-15 10:43
Indeed, I did not. However, with specifying the .csv file type, the size is still 0 bytes. See screenshot
![Bildschirmfoto 2020-04-15 um 12 41 30](https://user-images.githubusercontent.com/25327867/79328617-a441b880-7f16-11ea-861c-7d94c0a5bdb3.png)

**Comment by ghalter** [comment] 2020-04-15 10:48
Indeed, this happens with the given project, regardless of the file type. 
I'll take a look into it.

**Comment by flueko** [comment] 2020-05-21 19:05
Weird, did this problem occur again? @JStratil ?

**Comment by JStratil** [comment] 2020-05-22 09:07
In a new project with a test of imported AdA vocabulary, the csv-export seems to work without problems!
[New_Export_Test.csv.zip](https://github.com/ghalter/VIAN/files/4667071/New_Export_Test.csv.zip)

Here the project's eext-file:
[rezo_test.eext.zip](https://github.com/ghalter/VIAN/files/4667094/rezo_test.eext.zip)

I tested again the old project and it still didn't work (same with Thomas' project from the test session). Attached also the eext-file. (same project as posted above.)

[Capitalism.eext.zip](https://github.com/ghalter/VIAN/files/4667074/Capitalism.eext.zip)

Maybe it has/had to do with the vocabulary used?

**Comment by ghalter** [comment] 2020-05-22 13:59
Yes, interestingly, after I opened the file several time, the error mysteriously disappeared, and I could export the file correctly. I was however not yet able to find the root cause, but will look at it as soon as I implement the next sprint.

**Comment by ghalter** [comment] 2020-10-16 07:05
Has this ever occured again, or only in that one file?

**Comment by JStratil** [comment] 2020-10-16 11:02
Using Version 0.9.1 I could export a csv-file without problems from that file. It hasn't occured again.

**Comment by JStratil** [comment] 2020-10-16 13:52
I started the Colorimetry-analysis in that file and couldn't save it again. After reopening VIAN it worked. In two other newly created projects I didn't encounter this problem.

**Comment by JStratil** [comment] 2020-10-16 14:17
I had the same problem with another old project (couldn't export colorimetry after the analysis). In both cases VIAN crashed when I closed the project.

**Comment by JStratil** [comment] 2020-10-16 14:18
[Inside Job.eext.zip](https://github.com/ghalter/VIAN/files/5392251/Inside.Job.eext.zip)

This was the second project in which the error occured.

**Comment by JonathanSchaber** [comment] 2021-03-24 15:21
Is this still happening @JStratil ? Could not reproduce

**Comment by JStratil** [comment] 2021-03-29 11:57
No, it hasn't happened again. I have tested several projects and could export csv and colorimetry without errors.

**Comment by JonathanSchaber** [comment] 2021-03-29 12:04
closing this, problem seems to have disappeared

**Closed by JonathanSchaber** 2021-03-29 12:04 UTC
Labels: bug
