### ISSUE TITLE
project name can't be changed afterwards. 

### ISSUE THREAD

**Issue by megumihayakawa85** [ghalter/VIAN#266] opened 2020-03-13 11:29 UTC
I tried to change the project name afterwards, for example: "88_1_1_Three_Little_Pigs_1933_DVD" into "88_1_2_Three_Little_Pigs_1933_DVD", through opening project and changing information in INSPECTION. But even if I changed the name and saved it, the project name itself remains as the old one in VIAN programm. Next time when I open the file, I see the same old project name. 

here, I could change and SAVE the correct item number. 
![Anmerkung 2020-03-13 122604](https://user-images.githubusercontent.com/58776405/76617219-2446be00-6526-11ea-9dbf-f4e281a92130.png)

But here I couldn't save the correct information. I see still "1_1"
![Anmerkung 2020-03-13 122629](https://user-images.githubusercontent.com/58776405/76617301-4c362180-6526-11ea-91df-296f25e8cff2.png)

**Comment by ghalter** [comment] 2020-04-09 11:36
duplicate of #171

**Comment by ghalter** [comment] 2020-04-09 12:16
Fixed in commit c448d902

**Closed by ghalter** 2020-04-09 12:16 UTC
Labels: bug
